### ISSUE TITLE
InstallerKit failed to build from sources

### ISSUE THREAD

**Issue by vvs-** [RBornat/jape#1]
I'm trying to build Jape on NixOS and need to patch it in order to remove hardcoded paths as NixOS doesn't support FHS. It seems that jshortcut-0.4-oberzalek.jar is corrupt. Rebuilding it from sources is complicated also as it requires access to Windows development environment. Binaries seems to be available from Maven repositories though.

**Comment by RBornat** [comment]
The InstallerKit is the responsibility of my colleague Bernard Sufrin. I've forwarded your message to him.

Richard Bornat

**Comment by RBornat** [comment]
The shortcut stuff is not at all necessary for the Linux installer to
work, and the installer manifest for Linux doesn't reference it. I
suggest you remove the references to windows stuff in the build file for
the bootstrap installer before building it. It's only there at all
because I build the windows installers (on a linux machine) using the
same bootstrap.

You can ditch the stuff that gives rise to

62464 Sun Aug 01 20:51:06 BST 2010 jshortcut_amd64.dll
146944 Sun Aug 01 20:51:06 BST 2010 jshortcut_ia64.dll
 58368 Sun Aug 01 20:51:06 BST 2010 jshortcut_x86.dll
     0 Mon May 05 09:39:58 BST 2014 net/
     0 Mon May 05 09:39:58 BST 2014 net/jimmc/
     0 Mon May 05 09:39:58 BST 2014 net/jimmc/jshortcut/
   877 Mon May 05 09:39:58 BST 2014 net/jimmc/jshortcut/DUMMY.class
  5644 Sun Aug 01 20:51:06 BST 2010 net/jimmc/jshortcut/JShellLink.class

in the bootstrap installer jar. If you have the energy to look at the
java source (install.java) of the installer kit you could do it yourself
in half an hour or less. Add a -AlsoWindows switch to the command line
and look at its value before doing

>         jar.add(
>                 new File(WINDLLX),   // add the .dll file 
>                 new File(bootPath)  // ... to the bootstrap path
>                );
>         jar.add(
>                 new File(WINDLLY),   // add the .dll file 
>                 new File(bootPath)  // ... to the bootstrap path
>                );
>         jar.add(
>                 new File(WINDLLZ),   // add the .dll file 
>                 new File(bootPath)  // ... to the bootstrap path
>                );

and before doing

>        // 3. Add the DLL -- we know it's in the Jar because we put it there
>         jar.add(
>                 new URL(fromJar(WINDLLX)),
>                 new File(bootPath)
>                );
>         jar.add(
>                 new URL(fromJar(WINDLLY)),
>                 new File(bootPath)
>                );
>         jar.add(
>                 new URL(fromJar(WINDLLZ)),
>                 new File(bootPath)
>                );

You'll have to change the build.xml file so as not to unpack the various
(you say malformed) shortcut jars, and to leave the appropriate stuff
off the manifest.

If you're not up to this, and you're not in a rush, I might be able to
do it for you over the weekend; but I'd rather you did it yourself.

Bernard

**Comment by vvs-** [comment]
Sorry, I might have not made it clear. I've already solved this problem by downloading new binary `jshortcut-0.4-oberzalek.jar` from Maven. I've just opened this issue to let you know that this archive is corrupted in this GitHub repository.

**Comment by RBornat** [comment]
Thanks. 

Richard
