### ISSUE TITLE
Problems installing 9.1.0b on Windows with Spaces in Username

### ISSUE THREAD

**Issue by haz** [RBornat/jape#12]
Fielding a range of issues students have with 9.1.0 on both Win and Mac, but one that we've been able to narrow down and diagnose is spaces in the install path. If the username has a space, so will the install directory, and the installation doesn't work. Work around was to create a new user, install there, and gain access with admin rights from the original user's account (not ideal, but works for now).

Will post followup issues as we can characterize them better. For now, it's just MacOS not running the installed program at all, and hard to understand why -- creates a bar at the top with `Jape`, but no menus and no dialog box.

**Comment by RBornat** [comment]
Installs fine with a space in the installation directory. Investigations continue ... just going through the motions of creating a spaced-out user.

**Comment by RBornat** [comment]
I believe the problem is in the launchstub.bat file, which is in %LOCALAPPDATA%\Jape\Jape.app . I had forgotten to quote a couple of path strings. I can't manage to login to my VirtualBox Windows with a spaced username, so could you test it for me? I've had to zip the file to get it past github's policeman.

[launchstub.bat.zip](https://github.com/RBornat/jape/files/7171255/launchstub.bat.zip)

**Comment by RBornat** [comment]
I've started a new issue about the MacOS problem.

**Comment by haz** [comment]
More than just the .bat -- looks like the installation script (from the .exe call) fails because of the same reason:

![image](https://user-images.githubusercontent.com/225019/133470226-0f5e8d3a-2e03-40d7-80aa-50d2450ada30.png)

**Comment by AndrewHunter542** [comment]
I'm the student that had the issue with the space in my username. The problem was with the installation, not the `launchstub.bat` file. While the problem persisted, the `launchstub.bat` file was never created.

When I run the executable `JapeInstall_9.1.0b`, first, I would get a command prompt asking me to choose whether `JapeIn` is supposed to be a file or a directory. 

After choosing directory, inside the `JapeIn` folder was a bunch of nested folders with a file path: `...\JapeIn\Hunter\AppData\Local\Jape` (my user name is Andrew Hunter). 

Inside the `JapeIn` folder was also a shortcut was mapped to `C:\Users\Andrew Hunter\AppData\Local\Jape\Jape.app\launchstub.bat`, however, there was no folder called "Jape" inside `AppData\Local`, `C:\Users\Andrew Hunter\AppData\Local\Jape` did not exist. Since the shortcut was mapping to a file that didn't exist, it obviously didn't work.

There was nothing else in the `JapeIn` folder, including the absence of the `examples` folder.

So to be clear, after running the `launchstub.bat` executable, no files were actually created, including nothing in `AppData\Local`. 

The problem persisted wherever I put `JapeInstall_9.1.0b`, including different drives, and `C:\`. 

The workaround, as professor Muise said, was to create a new user without spaces in the name and run `JapeInstall_9.1.0b` while logged into the new user. This installed all the jape files, including the `launchstub.bat` file in `C:\Users\AltUser\AppData\Local\Jape\Jape.app`. After the installation was complete, I had no problem running the `launchstub.bat` file (which was still located in `C:\Users\AltUser\AppData\Local\Jape\Jape.app`) while logged in as my regular user (Andrew Hunter).

Hope this helps, let me know if you need any more details.

**Comment by RBornat** [comment]
Hello Andrew. I can't test my solutions on my local machine, because I can't login as a user with a space in their name. At least I haven't succeeded yet. Presumably you go in via a Microsoft account. Can you give any tips?

**Comment by RBornat** [comment]
I'm loading a possibly-working installer to DropBox, but syncing takes ages. So tomorrow (UK time) before I can even give you a download link.

**Comment by AndrewHunter542** [comment]
To create a new user with a space in the name, go to Settings, Accounts, Family & other users, then click Add someone else to this PC. Then click, "I don't have this person's sign-in information", then "Add a user without a Microsoft account", then you can create a user with a space in the user name. Be aware that it took me like 10 min to create a new user, and I was locked out of my PC during those 10 min. 

And just to let you know, while setting up the workaround was a little complicated, I can now use the workaround very easily, and I, personally, am not in any rush to get a fix.

**Comment by RBornat** [comment]
I can do that, but it won’t let me log in. The sign-in screen just says sign in wit work or school account, neither of which spacey the sailor has. I’d be happy to be locked out for a while. 

Richard

**Comment by RBornat** [comment]
local\ is the answer. So testing can at last proceed.

**Comment by RBornat** [comment]
9.1.0e is now released and solves this problem.
