### ISSUE TITLE
Add a web interface using WebAssembly?

### ISSUE THREAD

**Issue by teymour-aldridge** [RBornat/jape#2]
It would be cool if the project could be compiled for the web using [WebAssembly](https://webassembly.org/).

**Comment by RBornat** [comment]
Do have a look at the project before you say that. 

R

**Comment by teymour-aldridge** [comment]
Yes, I see what you mean. A lot of refactoring would be needed.

**Comment by RBornat** [comment]
A bit more than that. The display is controlled in Java, the proof engine is in ocaml, and they talk via a pipe ...

**Comment by teymour-aldridge** [comment]
I think that the Java code could be replaced with Javascript and either (a) the proof engine could be compiled for WebAssembly (a build target supported by most modern browsers) and then called from some Javascript code or the proof engine could be compiled using ReasonML (a language which enables Javascript and OCaml interoperability).

**Comment by RBornat** [comment]
Wow. Well, it’s public domain ...

Richard

**Comment by teymour-aldridge** [comment]
I’ll give it a go! (it may not work).

**Comment by teymour-aldridge** [comment]
Some thoughts I've had:
(a) there's a lot of Java code to be rewritten
(b) I'll need to do a lot of adjusting to the `OCaml` code so that it can run without an operating system – or set it up running on a web server somewhere.

**Comment by RBornat** [comment]
This is your project. I suspect it would be so much work it would be better to start again. 

I think that if you really intend to do it, just fork it into your own repo and go ahead. 

Richard

**Comment by teymour-aldridge** [comment]
I might try to port the core bits of the proof engine over and then rebuild everything else.

**Comment by EthanOrlander** [comment]
I had the same idea as you @teymour-aldridge to port this over to use a web interface. Professor Bornat, I know this is totally not your project, but I was hoping a couple minutes of your time might be able to save several weeks of mine. Here's the pitch: I think you are right that it could be best to do something of a rewrite if we're (I'm) talking web. However, you have already put significant effort into the current Jape engine, and there's huge value in that work. I was wondering:

1. Are there any design, brainstorming, notes, or really any documents you have that you would be willing to release? I am nowhere near as qualified nor as experienced as you are in the field, so if I am to have any chance of succeeding in a rebuild, it would be great to see some of your thoughts as you created and continued to maintain Jape. I've found [some of your papers about Jape](https://dblp.org/pid/49/5280.html), but wondering if there's anything else that you think could be of value to share for this endeavour.
2. Could you share some notes on what your development environment is for Jape, so that I can reproduce it on my machine. I intend to spend significant effort stepping through the program in a debugging environment so that I can produce something of a design schematic to inspire this 'v2'.

I understand this may be a lot to ask. However, I believe its is necessary if anyone less qualified than you, such as myself, is to fork off and modernize.

If nothing else, I appreciate you taking the time to read this comment.

Thanks!
Ethan

**Comment by teymour-aldridge** [comment]
Hi!
I plan to try to pick this up again (and I’d be happy to collaborate to do so).

My thoughts are:
1. The Java frontend is tricky to port over to run on the web and the reward for doing so is not high (it will not make for a nice user experience). Replacing it with an OCaml frontend makes sense (or we could use a standard Javascript frontend and pull in the OCaml engine as a library)
2. The important part is `camlengine`
	a. Currently this communicates through a pipe with the UI
	b. This is a nice interface boundary
	c. It makes sense to keep this separation in place, except that instead of using a pipe we can call the OCaml functions directly (but we should keep an interface separating UI code from proof logic because it makes things neater)

Additionally there were some weird problems I found using Facebook’s Reason compiler for Jape around language version compatibility. Life will be much easier using a different tool (e.g. `js_of_ocaml`) that takes OCaml bytecode and outputs Javascript from that, rather than also parsing, type checking, etc.

So the first step is to refactor the `camlengine` to work as an independent library, after which a UI should be added.

**Comment by EthanOrlander** [comment]
I like this plan of attack. I would vote for UI let's do TypeScript & React. I am very comfortable with these, and they're very widely used, which will be nice for getting more collaborators potentially. I guess we've got some other stuff to do before we worry about the new UI, though.

I also stumbled across JSOO. It looks cool, I'm going to take the next week or so to play around with it and the camlengine (separately). I saw in a previous post you said the engine talks to the filesystem. Not sure how JSOO handles this, but seeing as our environment is the browser I can't imagine it's graceful. I'll have to take a closer look, but I'm guessing we'll want to abstract any file access & state away from the engine itself. Are we on the same page here? Or maybe for the sake of getting something up and running ASAP, we can run the engine in node so it can get filesystem access. Lots to think about. I'll need some time to get familiar with the engine as it currently exists before I'm ready to start working on this.

**Comment by teymour-aldridge** [comment]
There are a couple of options:

- use Emscripten to fill in the functionality from the OS (this is treading off the beaten track though)
- refactor all the stuff communicating with an operating system to work in a browser

The second (imo) is easier to pull off.

**Comment by teymour-aldridge** [comment]
`js_of_ocaml` is nice because it operates directly on OCaml bytecode rather than being a fully-fledged compiler.

I'm currently somewhat busy writing some Rust/WebAssembly libraries, but hopefully I can find some time.

**Comment by RBornat** [comment]
I think you’ll have a problem making either side the master and the other a slave (subroutines). Currently it’s two parallel processes which ‘call’ each other in different ways. 

Richard

**Comment by teymour-aldridge** [comment]
Oh no – that does sound bad.

**Comment by RBornat** [comment]
> On 15 Jan 2021, at 23:45, Ethan Orlander <notifications@github.com> wrote:
> 
> 
> I had the same idea as you @teymour-aldridge <https://github.com/teymour-aldridge> to port this over to use a web interface. Professor Bornat, I know this is totally not your project, but I was hoping a couple minutes of your time might be able to save several weeks of mine. Here's the pitch: I think you are right that it could be best to do something of a rewrite if we're (I'm) talking web. However, you have already put significant effort into the current Jape engine, and there's huge value in that work. I was wondering:
> 
> Are there any design, brainstorming, notes, or really any documents you have that you would be willing to release? I am nowhere near as qualified nor as experienced as you are in the field, so if I am to have any chance of succeeding in a rebuild, it would be great to see some of your thoughts as you created and continued to maintain Jape. I've found some of your papers about Jape <https://dblp.org/pid/49/5280.html>, but wondering if there's anything else that you think could be of value to share for this endeavour.
There really aren't. No secrecy, but it was all done by direct discussion between Bernard and myself. Most of the development after about 1994 was done by me alone.
> Could you share some notes on what your development environment is for Jape, so that I can reproduce it on my machine. I intend to spend significant effort stepping through the program in a debugging environment so that I can produce something of a design schematic to inspire this 'v2'.
I edit source with BBEdit.

I use OCaml for the engine, via the command line in the MacOS Terminal app, with Unix tools like make. The build uses ocamlbuild, and no special libraries. At this instant I'm using OCaml 4.09.0, but jape can be compiled with later versions, I believe. I use opam to control my OCaml installation.

Aside from that I use Apache ant (Bernard introduced that, long after 1994, to control Java stuff). I used to use Eclipse to deal with Java, but it's very fussy and I'm not doing much Java development with jape at present, so currently I just use BBEdit. Eclipse is great, of course, if you are doing refactoring.

It's all held together with string and chewing gum and my memory. When I get a bug, or the urge to improve it, it usually takes me a week or so to work out how the bit I'm looking at does its work. I recently tried to 'improve' the underlying term datatype, and retired hurt.

There was once some discussion of how to organise the relationship between the Java (interface) and OCaml (engine). I can't remember why it was best to organise the launch so that the interface started first, but that's what happened. However it is not a master/slave relationship. When planning a proof display the interface is used rather like a subroutine, answering questions about the pixel size of rendered formulae and how big the window is and so on. When the user interacts with the proof the interface sends the engine a message but it doesn't get a reply: instead the engine tells the interface what to do and then goes to sleep till it gets another message.

One oddity is sub-formula selection (middle button on Windows/Linux; Alt+select on MacOS). The engine puts invisible-character brackets round each subformula, so selection doesn't choose just text, but rather a syntactically-correct subformula. 

Almost all the 'intelligence' is in the engine. Bernard doesn't like that.

There's a lot of complexity in the engine which is caused by our early naive intention (we're still pretty naive) to deal with all the logics which people might want to play with. We never did manage resource logics, and we never truly got into modal logic. But there's a resource-numbering mechanism, a spin-off of those attempts, which is very useful.

As you come across things, why not ask me about them? I'm retired now and have a good deal of free time.

Best wishes
Richard Bornat

**Comment by EthanOrlander** [comment]
Professor Bornat,

Thank you for the thorough response. This is exactly what I was looking for to get started. Now that I have the tools to debug the code, as well as your generous offer to provide some guidance, I'm going to see if I can compile a small team from my school to collaborate in this effort. We've got some great profs and students here, who specialize in all things from natural logic to design and all things computing. @teymour-aldridge and @RBornat, I'll reach out again once we have had a chance to get our hands dirty.

Ethan Orlander

**Comment by gogamid** [comment]
Hello,

any update on Web version of Jape?

**Comment by RBornat** [comment]
People sometimes see Jape, suppose that it’s really simple, and ask if it could be done on some entirely different technological base. Maybe it could: I dunno. But I doubt it would be easy. 

I think the guys who asked the question thought they could do it. Haven’t heard from them for a long time. 

Richard

**Comment by EthanOrlander** [comment]
Richard is right. Once I got to understanding the design and scope of Jape I dropped the idea of rebuilding. Beyond my abilities.

Ethan
